### ISSUE TITLE
Unable to start farming with windows binary 2.0.4 (Invalid payout address)

### ISSUE THREAD

**Issue by littleskunk** [Storj/storjshare-gui#366]
Windows binary is only possible with flatten-packages because of limited path lenght.

It is working without flatten-packages
```
npm install
npm start
```

It is not working with flatten-packages
```
npm install
flatten-packages app
npm start
```

The last command / the binary will always print out `Invalid payout address`
I end up here: https://github.com/bitpay/bitcore-lib/blob/master/lib/address.js#L418
```
"TypeError: _.any is not a function
    at Object.get (C:\storjshare-gui\build\node_modules\bitcore-lib\lib\networks.js:41:13)
    at Function.Address._classifyFromVersion (C:\storjshare-gui\build\node_modules\bitcore-lib\lib\address.js:165:36)
    at Function.Address._transformBuffer (C:\storjshare-gui\build\node_modules\bitcore-lib\lib\address.js:199:31)
    at Function.Address._transformString (C:\storjshare-gui\build\node_modules\bitcore-lib\lib\address.js:280:22)
    at Address._classifyArguments (C:\storjshare-gui\build\node_modules\bitcore-lib\lib\address.js:107:20)
    at new Address (C:\storjshare-gui\build\node_modules\bitcore-lib\lib\address.js:73:19)
    at Function.Address.getValidationError (C:\storjshare-gui\build\node_modules\bitcore-lib\lib\address.js:416:5)
    at Function.Address.isValid (C:\storjshare-gui\build\node_modules\bitcore-lib\lib\address.js:437:19)
    at UserData._isValidPayoutAddress (C:\storjshare-gui\build\lib\userdata.js:122:26)
    at UserData.validate (C:\storjshare-gui\build\lib\userdata.js:150:15)
    at Vue.startFarming (file:///C:/storjshare-gui/build/client.js:222:18)
    at HTMLButtonElement.<anonymous> (C:\storjshare-gui\build\node_modules\vue\dist\vue.common.js:216:54)"
```

**Comment by littleskunk** [comment]
_.any is removed with lodash@4. See https://github.com/lodash/lodash/wiki/Changelog#notable-changes

bitcore-lib requires lodash@3 https://github.com/bitpay/bitcore-lib/blob/master/package.json#L88

flatten-packages will delete old versions of the same package. If any of our dependencies and there dependencies updated to lodash@4 we have a problem.

Solution for this could be npm@3. It will create a flat package structure as well but it can handle different versions of the same package. I will try that later at home.

Another solution would be a hotfix. I could find the lodash@4 package and replace it with the latest lodash@3 package. Not perfect but quick and dirty .

**Comment by littleskunk** [comment]
Looks like npm@3 is working without any new problems. Time to update autobin build script and build a new binary.

**Comment by littleskunk** [comment]
windows binary looks good now. I updated OSX and Linux to npm@3 as well and will check these binaries now.
