### ISSUE TITLE
Uncaught Exception: Error: Could not locate the bindings file.

### ISSUE THREAD

**Issue by DaSpawn** [Storj/storjshare-gui#398]
### Versions

Replace the values below with your own:

- **GUI Version:** v2.0.9
- **Operating System:** Ubuntu 16.04

### Expected Behavior

Please describe the program's expected behavior.

```
program should open
```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Could not locate the bindings file. Tried:
 → /opt/storjshare/resources/app.asar/node_modules/leveldown/build/leveldown.node
 → /opt/storjshare/resources/app.asar/node_modules/leveldown/build/Debug/leveldown.node
 → /opt/storjshare/resources/app.asar/node_modules/leveldown/build/Release/leveldown.node
 → /opt/storjshare/resources/app.asar/node_modules/leveldown/out/Debug/leveldown.node
 → /opt/storjshare/resources/app.asar/node_modules/leveldown/Debug/leveldown.node
 → /opt/storjshare/resources/app.asar/node_modules/leveldown/out/Release/leveldown.node
 → /opt/storjshare/resources/app.asar/node_modules/leveldown/Release/leveldown.node
 → /opt/storjshare/resources/app.asar/node_modules/leveldown/build/default/leveldown.node
 → /opt/storjshare/resources/app.asar/node_modules/leveldown/compiled/6.1.0/linux/x64/leveldown.node
    at bindings (/opt/storjshare/resources/app.asar/node_modules/bindings/bindings.js:88:9)
    at Object.<anonymous> (/opt/storjshare/resources/app.asar/node_modules/leveldown/leveldown.js:4:46)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/opt/storjshare/resources/app.asar/node_modules/kfs/lib/s-bucket.js:4:17)

```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. ... install 2.0.9
2. ... try to open storjshare
3. ... fail without error, try to start from console and can see error

**Comment by littleskunk** [comment]
Looks like a problem with my linux build system. I will check for updates and build a new binary.

**Comment by littleskunk** [comment]
apt-get upgrade and latest nodejs version fixed it. Binary replaced. Please download and try again.
