### ISSUE TITLE
OS X build warning

### ISSUE THREAD

**Issue by littleskunk** [Storj/storjshare-gui#444]
> fs-xattr@0.1.14 install /Users/skunk/autobin/repos/storjshare-gui/node_modules/fs-xattr
> node-gyp rebuild

  CXX(target) Release/obj.target/xattr/src/async.o
  CXX(target) Release/obj.target/xattr/src/error.o
  CXX(target) Release/obj.target/xattr/src/sync.o
../src/sync.cc:46:59: warning: 'NewInstance' is deprecated
      [-Wdeprecated-declarations]
  v8::Local<v8::Object> actualBuffer = bufferConstructor->NewInstance(3...
                                                          ^
/Users/skunk/.node-gyp/6.9.1/include/node/v8.h:3270:31: note: 'NewInstance' has
      been explicitly marked deprecated here
                Local<Object> NewInstance(int argc, Local<Value> argv[]) const);
                              ^
/Users/skunk/.node-gyp/6.9.1/include/node/v8config.h:336:3: note: expanded from
      macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
  ^
1 warning generated.
  CXX(target) Release/obj.target/xattr/src/util.o
  CXX(target) Release/obj.target/xattr/src/xattr.o
  SOLINK_MODULE(target) Release/xattr.node

**Comment by littleskunk** [comment]
> fs-xattr@0.1.14 install /Users/skunk/autobin/repos/storjshare-gui/node_modules/fs-xattr
> node-gyp rebuild

gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: read ECONNRESET
gyp ERR! stack     at exports._errnoException (util.js:1026:11)
gyp ERR! stack     at TLSWrap.onread (net.js:569:26)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/skunk/autobin/repos/storjshare-gui/node_modules/fs-xattr
gyp ERR! node -v v6.9.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 

> macos-alias@0.2.11 install /Users/skunk/autobin/repos/storjshare-gui/node_modules/macos-alias
> node-gyp rebuild

gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: read ECONNRESET
gyp ERR! stack     at exports._errnoException (util.js:1026:11)
gyp ERR! stack     at TLSWrap.onread (net.js:569:26)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/skunk/autobin/repos/storjshare-gui/node_modules/macos-alias
gyp ERR! node -v v6.9.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok

**Comment by littleskunk** [comment]
It is located here: https://github.com/LinusU/fs-xattr/blob/fbd6659cf246764058a338cf748350e9f8004f5a/src/sync.cc#L46

The big question: Why has only OSX this problem? Maybe a simple system setting and I can compile without this warning / error?

**Comment by littleskunk** [comment]
Moved to https://github.com/LinusU/fs-xattr/issues/17

**Comment by littleskunk** [comment]
The build error was a problem with node-gyp on my osx build server. I don't know how but I was able to fix it.
