### ISSUE TITLE
Insufficient resources when creating new node 

### ISSUE THREAD

**Issue by moto456r** [Storj/storjshare-gui#548]
- **GUI Version:** v5
- **Operating System:** Windows 10 64bit

### Expected Behavior

Trying to create a new node

### Actual Behavior

GUI returns Insufficient resources error and also gives an invalid payout address error.

### Steps to Reproduce

Attempt to create new node in GUI

**Comment by MeijeSibbel** [comment]
```

assert.js:85
  throw new assert.AssertionError({
  ^
AssertionError: Table path is not a valid KFS instance
    at Btable._validateTablePath (C:\Program Files\Storj Share\resources\app\node_modules\kfs\lib\b-table.js:97:7)
    at Btable._open (C:\Program Files\Storj Share\resources\app\node_modules\kfs\lib\b-table.js:62:12)
    at new Btable (C:\Program Files\Storj Share\resources\app\node_modules\kfs\lib\b-table.js:51:10)
    at module.exports (C:\Program Files\Storj Share\resources\app\node_modules\kfs\index.js:15:34)
    at new EmbeddedStorageAdapter (C:\Program Files\Storj Share\resources\app\node_modules\storj-lib\lib\storage\adapters\embedded.js:30:14)
    at Object.<anonymous> (C:\Program Files\Storj Share\resources\app\node_modules\storjshare-daemon\script\farmer.js:24:3)
    at Object.<anonymous> (C:\Program Files\Storj Share\resources\app\node_modules\storjshare-daemon\script\farmer.js:88:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:428:7)
    at startup (bootstrap_node.js:147:9)
    at bootstrap_node.js:548:3
```

**Comment by littleskunk** [comment]
I agree. On a closer look `insufficient system resources` is a bug. A single core system will get this message on the first storjshare instance.

As workaround I could disable this feature and build a hotfix version.

@MeijeSibbel that looks like a second issue. See https://github.com/Storj/storjshare-daemon/issues/99

**Comment by WilhelmGGW** [comment]
Reporting: Same issue on migration on a single-node **Win 7** machine. The node started OK, but reported insufficient disc space and never populated the Shared field.

I exited storjshare and rebooted my computer. Then when I started StorjShare, everything settled in and reported correctly.

**Comment by tross2015** [comment]
I get the same warning at startup. All my nodes start but always one isn't complete I go to restart the node and get the warning
![resources](https://cloud.githubusercontent.com/assets/20988413/25659586/bf3e6148-3008-11e7-94af-82ef383aa82b.PNG)

**Comment by heunland** [comment]
Rocketchat user @webbah reported that he has experienced the above insufficient resources issue on Linux Mint Serena, he addressed it by adding RAM/CPU cores but still was unable to activate a 20GB node

**Comment by MrFancyMonocle** [comment]
https://github.com/Storj/storjshare-daemon/pull/121 should fix the resource issue on single-core machines, allowing a single share to be added. Each share that runs is running an entire farming node on the network, and the default of 1 process per share was added as a sane default; we'll definitely be looking at optimizing it, though, but most of that won't be a GUI issue. Meanwhile, in the storjshare-daemon CLI, running the storjshare-start command with an -u (--unsafe) flag will bypass the process check.

**Comment by WilhelmGGW** [comment]
![image](https://cloud.githubusercontent.com/assets/5957623/25699751/2947c3e6-308a-11e7-9a1d-cb513f2147d9.png)
On my Linux Mint install, initial startup after migration went perfectly normal for all 8 nodes. Then I edited the config file for the first node and attempted to restart it. That's when it threw this error and the node refused to start. All other nodes continue running normally.

Config for all nodes was set to allocate 0.001MB in V4. That's why you see all nodes with very high % full stats (in this image).

**Comment by MrFancyMonocle** [comment]
Closing, please continue discussion of any "Insufficient system Resources" issues in the https://github.com/Storj/storjshare-daemon project (there are probably several issue threads open now surrounding it). Any change to this behavior will take place there.
