### ISSUE TITLE
OpenError: Corruption: no meta-nextfile entry in descriptor

### ISSUE THREAD

**Issue by jfnz** [Storj/storjshare-gui#596]
### Versions

daemon: 2.5.4
core: 6.4.2
protocol: 1.1.0
nvm: v6.10.3
npm: '3.10.10',
ares: '1.10.1-DEV',
http_parser: '2.7.0',
icu: '58.2',
modules: '48',
node: '6.10.3',
openssl: '1.0.2k',
uv: '1.9.1',
v8: '5.1.281.101',
zlib: '1.2.11'

### Expected Behavior

```
Node starts when using storjshare-start command
```

### Actual Behavior

```
┌─────────────────────────────────────────────┬──────────┬──────────┬──────────┬──────────┬──────────┐
│ Share                                       │ Status   │ Uptime   │ Restarts │ Peers    │ Shared   │
├─────────────────────────────────────────────┼──────────┼──────────┼──────────┼──────────┼──────────┤
│ f9163e97d7a064bb29731cd07b1222d34f897fe0    │ stopped  │ 1s       │ 0        │ 0        │ ...      │
│   → /mount/ext-hdd-1/storj1                 │          │          │          │          │ (...%)   │
└─────────────────────────────────────────────┴──────────┴──────────┴──────────┴──────────┴──────────┘
```

```
events.js:160
      throw er; // Unhandled 'error' event
      ^
OpenError: Corruption: no meta-nextfile entry in descriptor
    at /usr/lib/node_modules/storjshare-daemon/node_modules/levelup/lib/levelup.js:119:34
    at /usr/lib/node_modules/storjshare-daemon/node_modules/abstract-leveldown/abstract-leveldown.js:39:16
```

### Steps to Reproduce

Unknown, random occurance

**Comment by littleskunk** [comment]
Duplicate: https://github.com/Storj/kfs/issues/55
