### ISSUE TITLE
Fatal Exception: ECONRESET causes Storj Share to crash.

### ISSUE THREAD

**Issue by MeijeSibbel** [storj/storjshare-gui#601]
### Versions

Replace the values below with your own:

- **GUI Version:** v5.0.1
- **Operating System:** windows 10

### Expected Behavior

Please describe the program's expected behavior.

```
Exception is handled properly. 
```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
After the exception Storj Share crashes. 
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. ...
2. ...
3. ...

### Screenshots (Optional)

![econreset](https://cloud.githubusercontent.com/assets/11735738/26455912/764bb2f8-4163-11e7-9f49-8248e61d0506.png)

**Comment by AlexeyALeonov** [comment]
After upgrade to the 5.1.0 node stopped after few hours of work.
Last from log:
```
{"level":"warn","message":"no proxy with id 440cf70c30bdcb51bc715223546de9b618350fc5 exists","timestamp":"2017-05-31T08:18:16.251Z"}
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at exports._errnoException (util.js:1022:11)
    at TCP.onread (net.js:572:26)
```
Start/Restart on node not helping.
After File-Quit and start node running (reaper).

**Comment by JukeboxRhino** [comment]
I receive this error a lot too, probably because of my home network but it causes the GUI to stop trying after 30 restarts which is the same as 5-8 hours roughly.

**Comment by AntonMZ** [comment]
I use storjshare-daemon
Version - daemon: 3.4.0, core: 6.6.0, protocol: 1.1.0
OS - CentOS Linux release 7.3.1611 (Core)
Linux localhost.localdomain 3.10.0-514.el7.x86_64 #1 SMP Tue Nov 22 16:42:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

My node starting, working 20sec and restarting.
After 25 restarts, node going to stopped status.
Destroy node and new start not resolve this problem.
Killall all nodes with daemon not resolve this problem too.

Record in node's log file.

`
Error: listen EADDRINUSE :::4003
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at Server._listen2 (net.js:1258:14)
    at listen (net.js:1294:10)
    at Server.listen (net.js:1390:5)
    at Server.listen (/root/.nvm/versions/node/v6.10.3/lib/node_modules/storjshare-daemon/node_modules/restify/lib/server.js:404:32)
    at Transport._bindServer (/root/.nvm/versions/node/v6.10.3/lib/node_modules/storjshare-daemon/node_modules/storj-lib/lib/network/transport.js:174:16)
    at Transport._open (/root/.nvm/versions/node/v6.10.3/lib/node_modules/storjshare-daemon/node_modules/storj-lib/lib/network/transport.js:104:17)
    at /root/.nvm/versions/node/v6.10.3/lib/node_modules/storjshare-daemon/node_modules/kad/lib/rpc.js:107:10
    at Transport.RPC._trigger (/root/.nvm/versions/node/v6.10.3/lib/node_modules/storjshare-daemon/node_modules/kad/lib/rpc.js:297:12)
    at Transport.RPC.open (/root/.nvm/versions/node/v6.10.3/lib/node_modules/storjshare-daemon/node_modules/kad/lib/rpc.js:106:8)
    at Transport.RPC (/root/.nvm/versions/node/v6.10.3/lib/node_modules/storjshare-daemon/node_modules/kad/lib/rpc.js:39:8)
    at new Transport (/root/.nvm/versions/node/v6.10.3/lib/node_modules/storjshare-daemon/node_modules/storj-lib/lib/network/transport.js:48:11)
    at FarmerInterface.Network._initNetworkInterface (/root/.nvm/versions/node/v6.10.3/lib/node_modules/storjshare-daemon/node_modules/storj-lib/lib/network/index.js:432:20)
    at FarmerInterface.Network (/root/.nvm/versions/node/v6.10.3/lib/node_modules/storjshare-daemon/node_modules/storj-lib/lib/network/index.js:80:8)
    at new FarmerInterface (/root/.nvm/versions/node/v6.10.3/lib/node_modules/storjshare-daemon/node_modules/storj-lib/lib/network/farmer.js:72:11)
events.js:160
      throw er; // Unhandled 'error' event
      ^
`

**Comment by maxp1256** [comment]
Same here.
GUI 6.1.0
Daemon 3.4.0
Core 6.6.0
Protocol 1.1.0

The drive does not start automatically after restarting.

**Comment by donAFRO** [comment]
I started receiving this error. I got three "miners" (1TB, 1TB and three 1TB drives in RAID 0 with Intel Rapid) So in total 5 TB in three locations.

When i receive this error the GUI in not responding but it seems it still uploads data based on Task manager...
<img width="353" alt="bug" src="https://user-images.githubusercontent.com/6069484/31149679-0c4d7612-a891-11e7-8e2a-7c0c85798201.png">

Win 10 64bit, 8GB ram, Intel xeon 8 cores
GUI: 7.1.0
Daemon: 5.1.0
Core: 8.1.0
Protocol: 1.2.0

**Comment by csfalcao** [comment]
![capturar2](https://user-images.githubusercontent.com/2768615/34280818-a59d6572-e6a1-11e7-943f-5c6b0803b282.JPG)
Just installed on Win 10 64, double click and boom, can't go on. Clicking restart worn't restart.

**Comment by krobbinsit** [comment]
![snip_20180110102652](https://user-images.githubusercontent.com/17711965/34826895-59b1f56e-f6a6-11e7-98c1-caa6be2fd173.png)

Same issue, I am running Windows 10 on a ESXI 6.5 VM.

**Comment by Tyvain** [comment]
Same here

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
