### ISSUE TITLE
Version 6 just gives a blank screen where only the top menu is visible.

### ISSUE THREAD

**Issue by alexeft** [Storj/storjshare-gui#624]
### Versions

Replace the values below with your own:

- **GUI Version:** v6.0.0
- **Operating System:** Debian 8 , has also been reported on Ubuntu 14.04

### Expected Behavior

Display the wizard to enter a new ethereum payment address. After the wizard is completed, proceed as normal.

```

```

### Actual Behavior

The payout address change wizard is never displayed after initial startup of gui ver 6.0.0. In a second attempt to start it, the normal window is displayed, only it is empty except for the top left menus (eg File->Quit)

```

```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Install version gui version5.1.0 and create a node on debian 8.
2. Remove version 5.1.0 and install version 6.0.0
3. Start gui. Nothing is displayed. Start it again and get a blank white screen.

**Comment by littleskunk** [comment]
I will check the linux binary later at home. I switched my linux build server and maybe missing to install or update something.

**Comment by littleskunk** [comment]
The binary is correct. Ubuntu 16.04 LTS is working fine.

Please open the gui from a command line promt and see if it prints out any error message. Developer console on the GUI is a good place to find errors as well.

**Comment by WilhelmGGW** [comment]
On my Linux Mint 17, the GUI will not even start. Only two processes start: storjshare & storjshare -type=zygote -no / But nothing more loads and the window never opens.  What is the command for opening the GUI from a command line prompt?

**Comment by WilhelmGGW** [comment]
Here is the error printout from running the GUI from command line:

/opt/storjshare/resources/app.asar/node_modules/bindings/bindings.js:83
        throw e
        ^

Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /tmp/.org.chromium.Chromium.gJcbTd)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:187:18)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at bindings (/opt/storjshare/resources/app.asar/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/opt/storjshare/resources/app.asar/node_modules/leveldown/leveldown.js:4:46)
    at Object.<anonymous> (/opt/storjshare/resources/app.asar/node_modules/leveldown/leveldown.js:109:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)

**Comment by dbobanj** [comment]
I have the same error on Ubuntu 14:

/opt/storjshare/resources/app.asar/node_modules/bindings/bindings.js:83
        throw e
        ^

Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /tmp/.org.chromium.Chromium.wOtmQz)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:187:18)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at bindings (/opt/storjshare/resources/app.asar/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/opt/storjshare/resources/app.asar/node_modules/leveldown/leveldown.js:4:46)
    at Object.<anonymous> (/opt/storjshare/resources/app.asar/node_modules/leveldown/leveldown.js:109:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)

**Comment by littleskunk** [comment]
Must be a missing dependency on my build server: https://github.com/atom/atom/blob/master/docs/build-instructions/linux.md#requirements

**Comment by dbobanj** [comment]
On Ubuntu 14 adding repository
sudo add-apt-repository ppa:ubuntu-toolchain-r/test 
and then doing:
apt-get install libstdc++6
fixes this issue and installs right version of GLIBCXX

**Comment by dbobanj** [comment]
If it doesn't install do sudo apt-get upgrade too.

**Comment by dbobanj** [comment]
getting
/opt/storjshare/storjshare: relocation error: /tmp/.org.chromium.Chromium.zjsWgf: symbol _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE9_M_createERmm, version GLIBCXX_3.4.21 not defined in file libstdc++.so.6 with link time reference
in log file so maybe not a full solution

**Comment by littleskunk** [comment]
A missing dependency on *my build server*

I will install the latest gcc compiler and build a new binary. Lets see if that helps.

**Comment by alexeft** [comment]
I receive the same error on debian 8.

Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /tmp/.org.chromium.Chromium.wOtmQz)
at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
at Object.Module._extensions..node (module.js:598:18)
at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:187:18)
at Module.load (module.js:488:32)
at tryModuleLoad (module.js:447:12)
at Function.Module._load (module.js:439:3)
at Module.require (module.js:498:17)
at require (internal/module.js:20:19)
at bindings (/opt/storjshare/resources/app.asar/node_modules/bindings/bindings.js:76:44)
at Object. (/opt/storjshare/resources/app.asar/node_modules/leveldown/leveldown.js:4:46)
at Object. (/opt/storjshare/resources/app.asar/node_modules/leveldown/leveldown.js:109:3)
at Module._compile (module.js:571:32)
at Object.Module._extensions..js (module.js:580:10)
at Module.load (module.js:488:32)
at tryModuleLoad (module.js:447:12)
at Function.Module._load (module.js:439:3)

I will for your fix littleskunk.

**Comment by littleskunk** [comment]
Should be solved now. Please download and install the latest version again.

**Comment by alexeft** [comment]
@littleskunk  Nope, that didn't work.

**Comment by littleskunk** [comment]
Same error message or a new one?

**Comment by alexeft** [comment]
Same

**Comment by littleskunk** [comment]
Looks like electron has some problems at the moment. I switched back to my old build server. Please download and install again. This time it has to work.
