### ISSUE TITLE
GUI 6.2.0 crash at start: Could not locate the bindings file

### ISSUE THREAD

**Issue by trotskylenin** [Storj/storjshare-gui#646]
### Versions

Replace the values below with your own:

- **GUI Version:** v6.2.0
- **Operating System:** Ubuntu 14.04

### Expected Behavior

Open and work normally.

```

```

### Actual Behavior

Crashing at start with the following error message:

```
/home/lenin/.nvm/versions/node/v6.9.1/lib/node_modules/storjshare-cli/node_modules/bindings/bindings.js:91
  throw err
  ^

Error: Could not locate the bindings file. Tried:
 → /home/lenin/.nvm/versions/node/v6.9.1/lib/node_modules/storjshare-cli/node_modules/leveldown/build/leveldown.node
 → /home/lenin/.nvm/versions/node/v6.9.1/lib/node_modules/storjshare-cli/node_modules/leveldown/build/Debug/leveldown.node
 → /home/lenin/.nvm/versions/node/v6.9.1/lib/node_modules/storjshare-cli/node_modules/leveldown/build/Release/leveldown.node
 → /home/lenin/.nvm/versions/node/v6.9.1/lib/node_modules/storjshare-cli/node_modules/leveldown/out/Debug/leveldown.node
 → /home/lenin/.nvm/versions/node/v6.9.1/lib/node_modules/storjshare-cli/node_modules/leveldown/Debug/leveldown.node
 → /home/lenin/.nvm/versions/node/v6.9.1/lib/node_modules/storjshare-cli/node_modules/leveldown/out/Release/leveldown.node
 → /home/lenin/.nvm/versions/node/v6.9.1/lib/node_modules/storjshare-cli/node_modules/leveldown/Release/leveldown.node
 → /home/lenin/.nvm/versions/node/v6.9.1/lib/node_modules/storjshare-cli/node_modules/leveldown/build/default/leveldown.node
 → /home/lenin/.nvm/versions/node/v6.9.1/lib/node_modules/storjshare-cli/node_modules/leveldown/compiled/6.9.1/linux/x64/leveldown.node
    at bindings (/home/lenin/.nvm/versions/node/v6.9.1/lib/node_modules/storjshare-cli/node_modules/bindings/bindings.js:88:9)
    at Object.<anonymous> (/home/lenin/.nvm/versions/node/v6.9.1/lib/node_modules/storjshare-cli/node_modules/leveldown/leveldown.js:4:46)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/lenin/.nvm/versions/node/v6.9.1/lib/node_modules/storjshare-cli/node_modules/kfs/lib/s-bucket.js:4:17)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)

```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Install version 6.2.0
2. Run storjshare in terminal
3. Crash

### Screenshots (Optional)

If the error is graphical in nature it is helpful to provide a screenshot.

**Comment by littleskunk** [comment]
You are calling the wrong application. `run storjshare in terminal` will call storjshare-daemon and not the GUI.
