### ISSUE TITLE
Can\'t set headers after they are sent

### ISSUE THREAD

**Issue by MeijeSibbel** [storj/storjshare-gui#694]
### Versions

Replace the values below with your own:

- **GUI Version:** 6.4.0
- **Operating System:** windows 7 x64

### Expected Behavior

Please describe the program's expected behavior.

```

```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
http_outgoing.js:367
throw new Error('Can\'t set headers after they are sent.');
^

Error: Can't set headers after they are sent.
at ServerResponse.setHeader (_http_outgoing.js:367:11)
at ServerResponse.format (C:\Program Files\Storj Share\resources\app\node_modules\restify\lib\response.js:147:10)
at ServerResponse.send (C:\Program Files\Storj Share\resources\app\node_modules\restify\lib\response.js:340:14)
at ReadableFileStream._handleReadFailure (C:\Program Files\Storj Share\resources\app\node_modules\storj-lib\lib\network\shard-server.js:257:11)
at emitOne (events.js:96:13)
at ReadableFileStream.emit (events.js:188:7)
at _sBucket._db.get (C:\Program Files\Storj Share\resources\app\node_modules\kfs\lib\read-stream.js:57:23)
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. ...
2. ...
3. ...

### Screenshots (Optional)

If the error is graphical in nature it is helpful to provide a screenshot.

**Comment by xyphos10** [comment]
GUI 6.4.0
Daemon 3.5.5
Core 6.8.0
Protocol 1.1.0

Operating System:

System Manufacturer: ASUSTeK Computer Inc.
Processor: Intel(R) Pentium(R) CPU B960 @ 2.20GHz (2 CPUs), ~2.2GHz
Memory: 6144MB RAM

Expected Behavior

The program should not restart by itself when downloading data to be stored (shards).

[logs.zip](https://github.com/Storj/storjshare-gui/files/1294015/logs.zip)

Actual Behavior

_http_outgoing.js:367
    throw new Error('Can\'t set headers after they are sent.');
    ^

Error: Can't set headers after they are sent.
    at ServerResponse.setHeader (_http_outgoing.js:367:11)
    at ServerResponse.format (C:\Program Files\Storj Share\resources\app\node_modules\restify\lib\response.js:147:10)
    at ServerResponse.send (C:\Program Files\Storj Share\resources\app\node_modules\restify\lib\response.js:340:14)
    at ReadableFileStream._handleReadFailure (C:\Program Files\Storj Share\resources\app\node_modules\storj-lib\lib\network\shard-server.js:257:11)
    at emitOne (events.js:96:13)
    at ReadableFileStream.emit (events.js:188:7)
    at _sBucket._db.get (C:\Program Files\Storj Share\resources\app\node_modules\kfs\lib\read-stream.js:57:23)

Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

...
...
...

**Comment by ne0ark** [comment]
It doesn't work well with netdrive or any mounted drive. Too much lag introduced.

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
