### ISSUE TITLE
Node cannot start/restart

### ISSUE THREAD

**Issue by calvintam236** [Storj/storjshare-gui#716]
### Versions

Replace the values below with your own:

- **GUI Version:** v7.1.0
- **Operating System:** macOS High Sierra 10.13

### Expected Behavior

Well, node is running.

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

Node cannot start/restart. 

```log
/Miner/Storj Share.app/Contents/Resources/app.asar/node_modules/storj-lib/lib/storage/item.js:81
  if (contact.hdKey) {
             ^

TypeError: Cannot read property 'hdKey' of undefined
    at StorageItem.getContract (/Miner/Storj Share.app/Contents/Resources/app.asar/node_modules/storj-lib/lib/storage/item.js:81:14)
    at /Miner/Storj Share.app/Contents/Resources/app.asar/node_modules/storj-lib/lib/network/shard-server.js:275:29
    at /Miner/Storj Share.app/Contents/Resources/app.asar/node_modules/storj-lib/lib/storage/manager.js:64:5
    at /Miner/Storj Share.app/Contents/Resources/app.asar/node_modules/storj-lib/lib/storage/adapter.js:64:5
    at /Miner/Storj Share.app/Contents/Resources/app.asar/node_modules/storj-lib/lib/storage/adapters/embedded.js:89:11
    at _getSbucketForKey (/Miner/Storj Share.app/Contents/Resources/app.asar/node_modules/kfs/lib/b-table.js:355:7)
    at Btable._getSbucketForKey (/Miner/Storj Share.app/Contents/Resources/app.asar/node_modules/kfs/lib/b-table.js:162:5)
    at Btable.createWriteStream (/Miner/Storj Share.app/Contents/Resources/app.asar/node_modules/kfs/lib/b-table.js:350:10)
    at _getShardStreamPointer (/Miner/Storj Share.app/Contents/Resources/app.asar/node_modules/storj-lib/lib/storage/adapters/embedded.js:82:9)
    at /Miner/Storj Share.app/Contents/Resources/app.asar/node_modules/storj-lib/lib/storage/adapters/embedded.js:93:7
    at _db.get (/Miner/Storj Share.app/Contents/Resources/app.asar/node_modules/kfs/lib/s-bucket.js:222:7)
/Miner/Storj Share.app/Contents/Resources/app.asar/node_modules/storjshare-daemon/lib/config/farmer.js:6
const datadir = path.join(homedir(), '.config', 'storjshare');
                          ^

Error: ENOENT: no such file or directory, uv_os_homedir
    at Object.<anonymous> (/Miner/Storj Share.app/Contents/Resources/app.asar/node_modules/storjshare-daemon/lib/config/farmer.js:6:27)
    at Object.<anonymous> (/Miner/Storj Share.app/Contents/Resources/app.asar/node_modules/storjshare-daemon/lib/config/farmer.js:48:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Miner/Storj Share.app/Contents/Resources/app.asar/node_modules/storjshare-daemon/script/farmer.js:8:42)
    at Object.<anonymous> (/Miner/Storj Share.app/Contents/Resources/app.asar/node_modules/storjshare-daemon/script/farmer.js:166:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
/Miner/Storj Share.app/Contents/Resources/app.asar/node_modules/storjshare-daemon/lib/config/farmer.js:6
const datadir = path.join(homedir(), '.config', 'storjshare');
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Start the node

**Comment by 4Ykw** [comment]
Have you done anything? Changed Storj folder?

It is complaining about not finding the folder that was expected.

**Comment by calvintam236** [comment]
No, I didn't. Looks like storjshare helper stuck when the GUI quits. manually kill them and reopen GUI fix it.

**Comment by calvintam236** [comment]
Just a note that someone reported the same error for `storjshare-daemon`.
https://github.com/Storj/storjshare-daemon/issues/258

**Comment by 4Ykw** [comment]
I am running both on Windows and Linux and have not yet encountered this problem.

**Comment by calvintam236** [comment]
It might be a bug that doesn't affect everyone. I am running it on macOS 10.13 High Sierra.
