### ISSUE TITLE
Storj node fails to start, Error: Table path is not a valid KFS instance

### ISSUE THREAD

**Issue by Kilo69** [storj/storjshare-gui#767]
### Versions

- **GUI Version:** v7.3.4
- **Operating System:** Windows 10 pro 1709, build 16299.309

### Expected Behavior

When opening storj program node should automatically start and connect.

### Actual Behavior

Node fails to start, even after system restart.

Log displays table path is not valid KFS instance.  However path has not change, is still accessible on drive.
{"level":"info","timestamp":"1522929053977","message":"Log file created."}
assert.js:60
  throw new errors.AssertionError({
  ^

AssertionError [ERR_ASSERTION]: Table path is not a valid KFS instance
    at Btable._validateTablePath (C:\Program Files\Storj Share\resources\app\node_modules\kfs\lib\b-table.js:97:7)
    at Btable._open (C:\Program Files\Storj Share\resources\app\node_modules\kfs\lib\b-table.js:62:12)
    at new Btable (C:\Program Files\Storj Share\resources\app\node_modules\kfs\lib\b-table.js:51:10)
    at module.exports (C:\Program Files\Storj Share\resources\app\node_modules\kfs\index.js:15:34)
    at new EmbeddedStorageAdapter (C:\Program Files\Storj Share\resources\app\node_modules\storj-lib\lib\storage\adapters\embedded.js:31:14)
    at Object.<anonymous> (C:\Program Files\Storj Share\resources\app\node_modules\storjshare-daemon\script\farmer.js:37:3)
    at Object.<anonymous> (C:\Program Files\Storj Share\resources\app\node_modules\storjshare-daemon\script\farmer.js:165:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:167:16)
    at bootstrap_node.js:589:3
assert.js:60
  throw new errors.AssertionError({
  ^

### Steps to Reproduce

Starting storj everytime causes issue

### Screenshots (Optional)

Could this be caused by file corruption?  I ran a CHKDSK on the drive no errors found.

Log settings and path for log/store

"loggerVerbosity": 4,
  // Path to write the log file to disk, leave empty to default to:
  // $HOME/.config/storjshare/logs/[nodeid].log
  "loggerOutputFile": "C:\\Users\\admin\\.config\\storjshare\\logs",
  // Directory path to store contracts and shards
  "storagePath": "C:\\Mining\\storj\\",

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
